### PR TITLE
allow replication of sublevels (nonbreaking)

### PR DESCRIPTION
**Pull request by nrw**
I'm not thrilled about the api for this, but I like that it's nonbreaking. I'm trying to allow `level-replicate` to be used to replicate a whole level instance so you can run a cluster of database instances where every node is a master. When a node is spawned, it can contact the other database nodes and start replication of all content (included changes made to sublevels). Is there a better way to do this API?

### CODE REVIEW

**Comment by nrw** [comment]
The API in the pull request looks like this:

``` js
var db1 = sublevel(level('db1'))
var db2 = sublevel(level('db2'))

var sub1 = db1.sublevel('data').sublevel('sub1')
var sub2 = db2.sublevel('data').sublevel('sub2')

var prefix = db1.sublevel('data').prefix() // prefix for data to replicate
var m1 = master(db1, 'master', 'M1', prefix)
var m2 = master(db2, 'master', 'M2', prefix)
```

**Comment by dominictarr** [comment]
Okay, this looks good - but what does the prefix do?
what is different than just doing:

``` js
var m1 = master(db1.sublevel('data'), 'master-data', MASTER_DATA_ID) 
```

**Comment by nrw** [comment]
the code you wrote will only replicate documents inserted directly into `db1.sublevel('data')`. so entries in `db1.sublevel('data').sublevel('documents')` will not replicate. my changes cause sub-sublevels to also replicate.

**Comment by dominictarr** [comment]
Oh, right.

Okay are you filtering out the sublevel that level-replicate creates? otherwise you'll end up replicating all the data twice... If you had a whitelist of sublevels that you wanted to replicate that would work.
or now that I think about it... Hmm, if I had used a convertion like `_name` for private sublevels (where the data is usually generated from other data - like a view) then you could just replicate the publically named sublevels...

**Comment by nrw** [comment]
the hook will throw an error if you try to replicate the `master` sublevel used by `level-replicate`. it throws something like `can't insert into own range`. the prefix option i added answers the question "what sublevel is the one with data in it?" 

The logic I added is expecting that the master sublevel and the data sublevel are siblings in the database you pass to `level-replicate`. Besides just documenting the usage, is there a path you want to take? are you proposing tackling this via changes to sublevel? is it feasible to try to mark sublevels as "replicate this" and "don't replicate this"?

**Comment by dominictarr** [comment]
Oh, right - so the data sublevel and all it's children are replicated? but not the master sublevel?
If you put a check inside the hook, you could just not insert a log when the master db is inserted into.
I think that would make for a cleaner solution than passing 3 different sublevels in.

also, `master` can be a sublevel that is not a child of `db`, so this would also work:

``` js
var db = level(...)
var data = db.sublevel('data')
var master = db.sublevel('master')
var replicate = Replicate(data, master, NODE_ID)
...
```

except you'd just have to pass in a thing to say you wanted this to hook everything recursively.

by the way - what are you using this for?
can you describe what your data is and what sort of thing you are storing in sublevels?

**Comment by nrw** [comment]
That's a good solution. I should be able to implement that pretty quickly.

My data looks like this:

```
- db root
  - data sublevel
    - sublevel full of docs indexed for searching
    - sublevel that i don't need to search
  - master sublevel
```

I'm only splitting data between sublevels because i want to apply different hooks for some data types (currently just indexing).

**Comment by nrw** [comment]
Looks like I need to do some more thinking on this. Here are the two areas i'm stuck on. Feel free to provide direction.
1. i can't do a check in the hook to see if were adding a doc to the master sublevel because the hook doesn't fire until after `add` throws [this error](https://github.com/dominictarr/level-hooks/blob/master/index.js#L108).
2. if i remove that error, i still need a string range that means "listen to everything, including what's in sublevels. plus, don't override my range setting with defaults along the way". this might require a change [here](https://github.com/dominictarr/string-range/blob/master/index.js#L46-L47). so far the best i have found is `{start: '\x00', end: '\xff\xff'}`. It feels hackish.

**Comment by nrw** [comment]
One more note about how i'm using this. I'm just replicating the whole level instance so i can avoid having a single point of failure. I've been using the code in this pull request in a project for a few days and it's working for that purpose quite well.

**Comment by dominictarr** [comment]
Ah, okay - do you also replicate the indexes?
or just rebuild the indexes on the replicants?
It would still be `{start: '\x00', end: '\xff\xff'}` anyway I think.
it is leaking the abstraction though, so maybe it should just be `{recursive: true}`
as the last argument.

hmm, that error shouldn't happen _unless_ you call add with something inside _master_.
it throws because that is a programmer error.  you'd just need to check here
https://github.com/dominictarr/level-replicate/blob/master/inject.js#L86
and return without calling add.

**Comment by nrw** [comment]
when we set the range for the pre hook to `{start: '\x00', end: '\xff\xff'}`, that makes the hook fire for everything with keys between `start` and `end`. [Here's the way I set up the hook](https://github.com/nrw/level-replicate/blob/replicate_sublevels/inject.js#L86). With that hook and this usage:

``` js
var db = level('/tmp/db')
var replicate = Replicate(db, 'master', NODE_ID)
```

anything in `db` or in a sublevel of `db` will trigger the hook. This includes the `master` sublevel. we're prevented from calling `add` in any useful way. by making the hook respond to everything in all sublevels, adds to `master` throw the `can't insert into own range` error. However, the alternative you proposed should work. This one:

``` js
var db = level(...)
var data = db.sublevel('data')
var master = db.sublevel('master')
var replicate = Replicate(data, master, NODE_ID)
```

I don't see a way to support both apis without changing the way `level-hooks` works. am i making sense?

**Comment by dominictarr** [comment]
If you insert into your own range that is normally an infinite loop, most times I've done that it's been an accident, but this case is an exception to that.

Okay - so the problem with my suggestion is that if you wanted to do a recursive replication you'd need to do two things: pass in `{recursive: true}` AND a different sublevel.

I don't like it when you have to do two things to activate one option.
An automatic car is easier to drive because you only have to push on the accelerator.
In a manual, you have to work the clutch and the gearbox simultaniously - that is a leaky abstraction.

Okay, so there needs to be an option in sublevel to NOT throw that error - it would be dangerous to use it directly, because it's fairly easy to do by accident and then you will get a RangeError which isn't very helpful - _however_ if you use `{recursive: true}` then `level-replicate` will set all the options for you... you merely have to set the correct option - that simple and safe.
OKAY

I've added unsafe mode for level-hooks: https://github.com/dominictarr/level-hooks#unsafe-mode

if you reinstall level-sublevel you'll get the latest level-hooks and you'll be able to pass in 
`{start: '\x00', end: '\xff\xff', safe: false}` and that will deactivate the error. That will simplify your pull request.

**Comment by nrw** [comment]
excellent. thanks for going to the extra trouble for this change. i'll send a PR soon.

**Comment by dominictarr** [comment]
no problem!

**Comment by nrw** [comment]
i think that last commit solves the problem as planned!

**Comment by nrw** [comment]
Is there anything left that's preventing this from getting merged?

**Comment by dominictarr** [comment]
some of the tests are failing for me. `test/net-replicate2.js` doesn't complete and test/replicate-sublevels.js has an error. hmm, `test/net-replicate2.js` doesn't complete on master either, so maybe a bug was introduced by a updated dep... it's probably gonna be a little harder to fix that one than the replicate-sublevels test. If you can figure out the sublevels one, I'll take the net-replicate2

**Comment by nrw** [comment]
these are passing for me. this sounds like a conversation we had in #17. i'm gonna try to get these passing on travis so i don't have to wonder what will pass on other machines (including yours) in the future.

**Comment by dominictarr** [comment]
hmm, sounds like it's probably a race condition which is something we need to fix anyway.
I made this module to test for race conditions https://github.com/dominictarr/interleavings
I've successfully found all sorts of weird stuff with it, but it would be a bit of work test leveldb with it. (it would require integrating it into memdown but would mean we could be much more confidant)

**Comment by nrw** [comment]
i'll take a look with interleavings. another (probably) useful note: tests pass in node `0.10` and fail in `0.8`: https://travis-ci.org/nrw/level-replicate/builds/28059981

**Comment by dominictarr** [comment]
yeah, and it looks like one of the tests just doesn't finish which is what I am seeing locally.

**Comment by nrw** [comment]
extending the timeouts like the one [here](https://github.com/nrw/level-replicate/blob/master/test/net-replicate-msgpack.js#L49) makes the net replicate tests pass on 0.8 for me. i'm hunting for what event to hook onto instead of waiting. if you already know what i should wait for, please share. :)

**Comment by nrw** [comment]
found one of our issues: in `0.8.26`, the testing tools in `test/util.js` don't allow the tests to end properly. one issue is that [this timeout](https://github.com/nrw/level-replicate/blob/master/test/util.js#L23) holds the process open by continuing to fire on repeat after the stream has ended.

**Comment by dominictarr** [comment]
okay adjusting the timeouts does not fix the race condition.
I found something that looked wrong though - tail was false but it should have been taken from the options.
I fixed that, and eventually realized that I hadn't upgraded level-sublevel...
every thing is now passing for me, and I have merged this into 1.2.0!
Thanks for all your hard work!

**Comment by dominictarr** [comment]
Looking back at this code again, after something like a year since I wrote it makes me think I can probably do much better, and since I'm working on a similar protocol over at https://github.com/dominictarr/secure-scuttlebutt
I might give this style of replication another go.

**Comment by nrw** [comment]
so this won't be merged?

**Comment by dominictarr** [comment]
oops, sorry I had merged it into my local copy of your branch but I forgot to merge it with master.
merged into 1.2.1

**Comment by nrw** [comment]
yay! thanks!

**Pull request merged**
