### PR TITLE
key fidelity test. match code formatting better.

### PR DESCRIPTION
**Pull request by nrw**
I believe I handled the issues discussed in #16. I didn't find a way to make this test fail and pass in the same way using the `populate` helper. As I only need one value to show this bug and it only happens when you close and re-open the database, `populate` didn't make the test any simpler. I think the important thing is this test shows the bug I found being solved, right?

### CODE REVIEW

**Comment by nrw** [comment]
I just updated this to eliminate the race condition in the test.

**Comment by dominictarr** [comment]
I can't run this test I just get this error:

``` js
level-replicate(mangle3)>node test/key-fidelity.js 
TAP version 13
# setup
# fills

/home/dominic/c/level-replicate/node_modules/tape/index.js:75
        throw err
              ^
TypeError: Cannot call method 'iterator' of null
    at /home/dominic/c/level-replicate/node_modules/level-test/node_modules/levelup/lib/levelup.js:400:24
    at LevelUP.<anonymous> (/home/dominic/c/level-replicate/node_modules/level-test/node_modules/levelup/lib/read-stream.js:63:24)
    at LevelUP.g (events.js:180:16)
    at LevelUP.EventEmitter.emit (events.js:117:20)
    at /home/dominic/c/level-replicate/node_modules/level-test/node_modules/levelup/lib/levelup.js:122:12
```

my guess is that your version of levelup is old. I have `levelup@0.18.2`
can you post `npm ls`? also, merge with master and do a fresh install of all your node_modules?

**Comment by dominictarr** [comment]
also, I updated the net replicate tests, so make sure your next pull request merges with master.

**Comment by dominictarr** [comment]
Okay, I reinstalled everything, but still get the iterator not found error.
I think this might be about closing the database? maybe this is even a levelup issue.
my immediate question though, is how are you not getting this error?

**Comment by nrw** [comment]
With a fresh clone of your master branch and `npm install`, tests pass for me. When I then swap in [this version](https://github.com/nrw/level-replicate/blob/no_race_condition/test/key-fidelity.js) of the test that has no race condition, tests also pass. I don't know why this won't run for you. :P

I'm on a mac? does that matter?

```
$ npm --version
1.4.3
$ node --version
v0.10.26
```

here's `npm ls`:

```
level-replicate@1.1.7 /Users/nrw/dev/node-packages/level-replicate
├─┬ continuable-para@1.0.2
│ ├─┬ continuable-hash@0.1.4
│ │ └── continuable@1.1.8
│ └─┬ continuable-list@0.1.6
│   └── continuable@1.1.8
├── continuable-series@1.1.0
├─┬ json-buffer@2.0.7
│ └─┬ bops@0.0.6
│   ├── base64-js@0.0.2
│   └── to-utf8@0.0.1
├─┬ level-sublevel@5.2.0
│ ├─┬ level-fix-range@2.0.0
│ │ └── clone@0.1.11
│ ├── level-hooks@4.4.5
│ ├── string-range@1.2.2
│ └─┬ xtend@2.0.6
│   ├── is-object@0.1.2
│   └─┬ object-keys@0.2.0
│     ├── foreach@2.0.4
│     ├── indexof@0.0.1
│     └── is@0.2.7
├─┬ level-test@1.6.2
│ ├─┬ level-js@1.0.8
│ │ ├── abstract-leveldown@0.7.2
│ │ ├── idb-wrapper@1.2.0
│ │ └── isbuffer@0.0.0
│ ├─┬ leveldown@0.10.2
│ │ ├── bindings@1.1.1
│ │ └── nan@0.6.0
│ ├─┬ levelup@0.18.2
│ │ ├─┬ bops@0.1.1
│ │ │ ├── base64-js@0.0.2
│ │ │ └── to-utf8@0.0.1
│ │ ├── concat-stream@0.1.1
│ │ ├─┬ deferred-leveldown@0.1.0
│ │ │ ├── abstract-leveldown@0.10.2
│ │ │ └─┬ bops@0.0.7
│ │ │   ├── base64-js@0.0.2
│ │ │   └── to-utf8@0.0.1
│ │ ├── errno@0.1.1
│ │ ├── prr@0.0.0
│ │ ├─┬ readable-stream@1.0.26-2
│ │ │ └── string_decoder@0.10.25-1
│ │ └── semver@2.2.1
│ ├─┬ memdown@0.6.0
│ │ ├── abstract-leveldown@0.11.4
│ │ └─┬ bops@0.1.1
│ │   ├── base64-js@0.0.2
│ │   └── to-utf8@0.0.1
│ ├── osenv@0.0.3
│ └─┬ xtend@2.1.2
│   └── object-keys@0.4.0
├── monotonic-timestamp@0.0.8
├─┬ msgpack-stream@0.0.11
│ ├─┬ bops@0.0.6
│ │ ├── base64-js@0.0.2
│ │ └── to-utf8@0.0.1
│ ├── msgpack-js@0.3.0
│ └── through@2.3.4
├── observable@2.1.3
├─┬ pull-cat@1.1.5
│ └── pull-core@1.0.0
├── pull-crypto@1.0.3
├─┬ pull-level@1.1.10
│ ├── level-fix-range@1.1.4
│ ├─┬ level-post@1.0.3
│ │ └── string-range@1.2.2
│ ├─┬ pull-pushable@1.1.4
│ │ └─┬ pull-stream@2.18.3
│ │   └── pull-core@1.0.0
│ ├─┬ pull-window@2.1.2
│ │ ├── looper@2.0.0
│ │ └── pull-core@1.0.0
│ └─┬ stream-to-pull-stream@1.3.1
│   └── pull-core@1.0.0
├─┬ pull-stream@2.21.0
│ └── pull-core@1.0.0
├─┬ pull-stream-merge@1.0.4
│ └─┬ pull-pushable@1.1.4
│   └─┬ pull-stream@2.18.3
│     └── pull-core@1.0.0
├─┬ pull-stream-to-stream@1.2.6
│ └── pull-core@1.0.0
├─┬ pull-window@1.0.3
│ └── pull-core@1.0.0
├─┬ pull-zip@1.0.2
│ └── pull-core@1.0.0
├── random-name@0.1.0
├── rimraf@2.2.6
├── shasum@0.0.2
├─┬ stream-combiner@0.0.2
│ └── duplexer@0.0.4
├── stream-serializer@1.1.2
├─┬ stream-to-pull-stream@1.2.3
│ └── pull-core@1.0.0
└─┬ tape@2.10.2
  ├── deep-equal@0.2.1
  ├── defined@0.0.0
  ├─┬ glob@3.2.9
  │ └─┬ minimatch@0.2.14
  │   ├── lru-cache@2.5.0
  │   └── sigmund@1.0.0
  ├── inherits@2.0.1
  ├── object-inspect@0.3.1
  ├── resumer@0.0.0
  └── through@2.3.4
```

**Comment by dominictarr** [comment]
aha, it's caused by iterator cleanup. if I comment all the tests except `fills` and then comment `db.close...` it doesn't error, if I uncomment `db.close...` it errors.

**Comment by dominictarr** [comment]
this might be a levelup/down error.
maybe you can reproduce this by running test on travis (if it's about linux, weird that it would be though)?
I can't merge this if it's not working for me.

**Comment by dominictarr** [comment]
maybe the test can be written differently, or the specific bit tracked down?
the data you showed me looked like something being JSONed repeatedly.
maybe you could put an assertion in the code that asserted it parsed valid json and gave an object with the shape.

**Comment by nrw** [comment]
closing as i'm looking at other ways to do this.

**Pull request closed without merging**
