### PR TITLE
slave key and value encoding must also be explicit. plus key mangling test

### PR DESCRIPTION
**Pull request by nrw**
This solve a problem very similar to #15 but on the slave stream instead of the master stream. This has the strange symptom of causing data to randomly disappear.

### CODE REVIEW

**Comment by dominictarr** [comment]
can you use level-test (like the other tests) instead of level and rimraf?
that should make running the tests on other platforms (browser, etc) easier

**Comment by nrw** [comment]
Yes. I'll update the test and resubmit.

**Comment by dominictarr** [comment]
I can't get this test to pass. maybe because I merged your other pr?
can you look at my mangle branch and see if you can figure it out?

also, I already have helpers for populating the database - It's probably best if you use those, or do the same style.

**Comment by dominictarr** [comment]
pull from my mangle branch and use that. I've already merged some stuff...

**Comment by dominictarr** [comment]
oh, I've just updated pull-stream and pull-level to latest, and the tests work now.
please pull the latest master.

**Comment by dominictarr** [comment]
your test seems to contain some race conditions. sometimes I get object has no property `iterator` and sometimes it works. 

Also, you fill the database (by saving just one key) but then the test runs 4 times...
but the data is copied after the first time, so what does the later tests check?

that said, there is also something weird happening in the net-replicate tests.

unfortunately this stuff is quite hard to test.

**Comment by nrw** [comment]
Looks like we commented at the same time. :) More details about this bug:

In a replicated database with a value in it, you close the database, reopen the database, and start replication again. In the `clock` database, a key that should be "foo" comes out like this:

```
expected: "foo"
actual:   "\"foo\""
```

Escaping happens on each new replication. So, by the fourth open it looks like this:

```
expected: "foo"
actual:   "\"\\\"\\\\\\\"foo\\\\\\\"\\\"\""
```

**Comment by nrw** [comment]
Also, I realize it has a race condition. I've made a version without one. I'll send it in a moment.

**Comment by dominictarr** [comment]
oh, hmm, yes that is wrong. that means we need a test with opening and closing too.

**Pull request closed without merging**
